kind: ConfigMap
apiVersion: v1
metadata:
  name: general-config
data:
  datasource.url: "jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/postgres"
  datasource.initSql: "CREATE TABLE clients (\n\tclient_id SERIAL PRIMARY KEY,\n\tname VARCHAR ( 50 ) NOT NULL,\n    age INT\n);"
  datasource.address: "postgres-postgresql.default.svc.cluster.local"


