apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    metadata:
      name:  init-db
      labels:
        app: init-postgresdb
    spec:
      containers:
        - image: "docker.io/bitnami/postgresql:15.2.0-debian-11-r0"
          name: init-db
          command: [ "/bin/bash", "-c", "psql -U postgres -d $(PGDATABASE) -c '$(INITDB)'" ]
#          command: [ "psql '$(INITDB)'" ]
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: general-config
                  key: datasource.address
            - name: PGDATABASE
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: bd-secret
                  key: datasource.password
            - name: INITDB
              valueFrom:
                configMapKeyRef:
                  name: general-config
                  key: datasource.initSql

      restartPolicy: OnFailure